IF	OBJECT_ID('dbo.FN_RootCustomer') IS NULL
	EXEC ('CREATE FUNCTION dbo.FN_RootCustomer() RETURNS int AS BEGIN RETURN 0 END')
GO

ALTER FUNCTION	dbo.FN_RootCustomer()
RETURNS int
AS
BEGIN
	RETURN 11209
END
GO
